import type { MoodId, TagId } from './moods';
import type { CellId } from './grid';

/**
 * Shared contracts between server, simulator, and frontend.
 * Everything the API returns is defined here — treat this file as the
 * source of truth.
 */

/** k-anonymity: cells with fewer reports than this are never returned. */
export const K_ANONYMITY = 5;

/** Rolling aggregation window shown on the map, in minutes. */
export const DEFAULT_WINDOW_MINS = 60;

/** How much history the store retains (and the sim seeds), in hours. */
export const RETENTION_HOURS = 48;

// ---------------------------------------------------------------------------
// Reports & store
// ---------------------------------------------------------------------------

/**
 * What a client submits. Raw lat/lng — snapped server-side, never stored.
 * lat/lng must be provided together or omitted together; when omitted, the
 * server derives a coarse location from the connection's IP (which is used
 * only in memory for that lookup and for rate limiting — never stored).
 */
export interface MoodReportInput {
  mood: MoodId;
  lat?: number;
  lng?: number;
  tag?: TagId;
}

/**
 * What the store keeps. lat/lng are ALREADY snapped to the center of the
 * finest grid cell (see shared/grid.ts snapToFinest). No user identifier,
 * no IP, no raw location, ever.
 */
export interface StoredReport {
  t: number; // epoch ms
  mood: MoodId;
  lat: number; // snapped
  lng: number; // snapped
  tag?: TagId;
  sim: boolean; // true = generated by the world simulator
}

/** In-process store interface shared by server, simulator, and tests. */
export interface ReportStore {
  insert(r: StoredReport): void;
  /** All reports with fromT <= t < toT, unordered. */
  query(fromT: number, toT: number): StoredReport[];
  count(): number;
  /** Subscribe to inserts; returns an unsubscribe function. */
  onInsert(cb: (r: StoredReport) => void): () => void;
  /** Drop reports older than the retention horizon. */
  prune(olderThanT: number): number;
}

// ---------------------------------------------------------------------------
// API responses
// ---------------------------------------------------------------------------

export interface AggregateCell {
  cellId: CellId;
  count: number;
  valence: number; // count-weighted mean, -1..1
  energy: number; // count-weighted mean, 0..1
  topMood: MoodId;
  moods: Partial<Record<MoodId, number>>; // counts per mood
}

export interface AggregatesResponse {
  res: number;
  windowMins: number;
  /** Window end (epoch ms) the aggregation was computed for. */
  at: number;
  k: number;
  cells: AggregateCell[];
  totalReports: number; // reports in window across ALL cells (pre-threshold)
}

export interface TrendPoint {
  t: number; // bucket start, epoch ms
  count: number;
  valence: number;
  moods: Partial<Record<MoodId, number>>;
}

export interface TrendsResponse {
  bucketMins: number;
  points: TrendPoint[]; // oldest → newest; empty buckets have count 0
}

export interface Mover {
  cellId: CellId;
  label: string; // nearest major city, e.g. "near Tokyo, JP"
  deltaValence: number; // current window vs previous window
  valence: number;
  count: number;
}

export interface InsightsResponse {
  at: number;
  global: {
    count: number;
    valence: number;
    energy: number;
    topMoods: Array<{ mood: MoodId; count: number }>;
  };
  movers: Mover[]; // sorted by |deltaValence|, max 5
}

/** One crypto donation option (public receive address — safe to publish). */
export interface CryptoAddress {
  label: string; // e.g. "ETH & USDT ERC-20"
  address: string;
}

export interface MetaResponse {
  k: number;
  windowMins: number;
  retentionHours: number;
  resolutions: readonly number[];
  startedAt: number;
  simulated: boolean;
  /** SUPPORT_URL env (donations page); null when unset. */
  supportUrl: string | null;
  /** SUPPORT_CRYPTO env ("Label:address,Label:address"); empty when unset. */
  supportCrypto: CryptoAddress[];
}

export interface ReportAccepted {
  ok: true;
  cellId: CellId; // finest-res cell the report was snapped to
}

/**
 * GET /api/geo — the coarse location the server would assign to this
 * connection (proxy geo headers, else local GeoLite2 lookup). Returns the
 * CENTER of the snapped finest-res cell, never the raw lookup result.
 */
export interface GeoResponse {
  ok: true;
  cellId: CellId;
  lat: number; // snapped cell center
  lng: number;
  /** e.g. "near London, GB" (nearest major city) — null if unknown */
  label: string | null;
}

/** GET /api/health — liveness/readiness for deploy platforms. */
export interface HealthResponse {
  ok: true;
  uptimeSec: number;
  reports: number;
  simulated: boolean;
}

export interface ApiError {
  ok: false;
  error: string;
}

// ---------------------------------------------------------------------------
// SSE events on GET /api/stream
// ---------------------------------------------------------------------------

/** event: update — throttled signal that aggregates changed. */
export interface UpdateEvent {
  at: number;
  totalReports: number;
}

/**
 * event: pulse — a single anonymized report ticker item. Location is
 * coarsened to resolution 0 (10°, continent scale) before broadcast.
 */
export interface PulseEvent {
  mood: MoodId;
  cellId: CellId; // ALWAYS resolution 0
  at: number;
}

// ---------------------------------------------------------------------------
// Simulator contract (server/sim/index.ts must export exactly these)
// ---------------------------------------------------------------------------

export interface SimOptions {
  /** epoch ms treated as "now" for seeding */
  now: number;
  /** hours of history to backfill (default RETENTION_HOURS) */
  hours?: number;
  /** RNG seed for deterministic output (default 42) */
  seed?: number;
}

export interface City {
  name: string;
  country: string; // ISO-3166 alpha-2, e.g. "JP"
  lat: number;
  lng: number;
  pop: number; // metro population, used as report-rate weight
}
